#! /bin/sh

xsetroot -cursor_name left_ptr
xrandr --output DisplayPort-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-1 --off --output DVI-0 --off --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal
feh --bg-fill /hdd/Wallpapers/All/rivendell.jpg

xbindkeys &
xautolock -time 5 -locker ~/bin/lock-screen -killtime 15 -killer "systemctl suspend" -detectsleep &
compton -b --config ~/.config/compton/compton.conf &
sxhkd &
polybar top &
polybar left &


bspc monitor HDMI-0 -d I II III IV V 
bspc monitor DisplayPort-0 -d VI VII VIII IX X

#bspc config border_width         2
#bspc config window_gap          12

bspc config border_width         0
bspc config normal_border_color  "#191919"
bspc config focused_border_color "#2F2F2F"
bspc config window_gap           50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

bspc config pointer_mod mod1
bspc config pointer_action1 move

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating
